### ISSUE TITLE
Composer.json support ?

### ISSUE THREAD

**Issue by barberob** [baptistelechat/codeX#8]
This extension is super useful ! Do you plan on adding a similar system for php devs, using the project's composer.json?

**Comment by baptistelechat** [comment]
Hello @barberob, 

Thank you very much for your feedback !

A CodeX update is coming soon but will not yet support composer.json. It will correct a lot of bugs that have been reported to me and add an essential feature to the extension.

This request for composer.json support for PHP developers has already been reported to me and is already in my roadmap for the next update. 

I'll get back to you as soon as it's ready. 😉

**Comment by baptistelechat** [comment]
Hi @barberob,

Good news, CodeX officially supports the composer.json file! So now you have all the dependency documentation in your PHP project.

I'm not a PHP expert (more Typescript), so let me know if you run into any bugs 😉

I've written a thread on Twitter (X) if you want to know more. I'm French, so it's not written in English : https://x.com/baptiste_lechat/status/1830514975657390323

I'll close this GitHub issue if everything looks ok to you. Anyway, I look forward to hearing from you! 😁

**Comment by barberob** [comment]
Nice! it seems to work great for me 😃 thanks for the help and the nice work!

**Comment by baptistelechat** [comment]
Amazing! Thanks to you for your feedback on my project 🙏 I'll be able to close this first GitHub Issue 🗃️
